name: Release to PyPI

on:
  release:
    types: [released]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Check out Pulser
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools build

  check-release:
    needs: deploy
    env:
      # Set Matplotlib backend to fix flaky execution on Windows
      MPLBACKEND: Agg
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Check out Pulser
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pulser from PyPI
        timeout-minutes: 5
        shell: bash
        run: |
          python -m pip install --upgrade pip
          version="$(head -1 VERSION.txt)"
          until pip install pulser==$version
          do
            echo "Failed to install from PyPI, will wait for upload and retry."
            sleep 30
          done
      - name: Test the installation
        shell: bash
        run: |
          version="$(head -1 VERSION.txt)"
          python -c "import pulser; assert pulser.__version__ == '$version'"
          grep -e pytest dev_requirements.txt | sed 's/ //g' | xargs pip install
          pytest
